
export default function Home() {

  return (
    <div>
      <p className="h1-bold text-dark400_light900 mb-6">my project</p>

      <p className="text-dark400_light900">
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quidem, tempora reprehenderit! Fugiat impedit, tempore saepe esse earum velit consectetur perspiciatis corporis optio quae facere eum hic recusandae minima, sit, nisi reiciendis deleniti dolor. Maxime modi corporis laudantium ad fugiat, dolores asperiores voluptatibus architecto nisi, repellat ipsum totam ullam! Harum ullam a, possimus in distinctio quidem nesciunt autem corrupti nulla, vel vero inventore, sequi nobis sint dolorum hic deserunt! Delectus, rem tempore. Illo in magni aliquam nihil itaque labore. Nam quod amet itaque quas doloremque. Ea culpa suscipit rerum nobis, esse, expedita vero eveniet mollitia quidem incidunt eum, veritatis quibusdam deserunt voluptates doloribus tempora recusandae qui dolorum obcaecati illum! Unde, molestiae dolorum placeat veniam, ratione, ex quas qui doloribus eius fugit incidunt recusandae vel? Corrupti, quia tenetur cum dolores doloribus id cupiditate quidem nesciunt expedita. Quo excepturi voluptas amet ipsum sapiente, eos eligendi, autem, commodi cum tempore ut aut? Ipsam illum maxime dolore error aperiam et consequatur sapiente soluta fuga eveniet quas eos, tempora deserunt eaque earum quasi quibusdam perspiciatis illo. Facilis eum totam adipisci modi dolores voluptatibus commodi porro saepe ipsum dicta nostrum, fugiat facere laborum praesentium esse, consequatur iste iure rem. Voluptatem excepturi cupiditate ab quo. Facilis, maxime error iusto ea nemo fugiat! Quasi veritatis, commodi vero obcaecati velit possimus minus aut eveniet, totam esse quae temporibus impedit accusantium maxime doloremque repellat sunt magnam cum dolore officiis! Quam minima dolore cumque blanditiis voluptatem, ipsum nostrum veniam beatae eaque perferendis? Aspernatur excepturi reprehenderit nulla quibusdam, praesentium ex ipsum vero veniam quae animi magnam dolore quasi, hic labore consectetur eos. Repellat fugiat aspernatur libero ut, corporis tenetur ea dignissimos, eaque, excepturi veniam esse minima quaerat repudiandae cumque ipsum at illo nemo atque! Deleniti nobis magnam vero voluptatibus sint totam quos. Officiis eligendi nam qui. Accusantium incidunt autem quaerat doloremque repellat! Tenetur.

      </p>
      <p className="text-dark400_light900">
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quidem, tempora reprehenderit! Fugiat impedit, tempore saepe esse earum velit consectetur perspiciatis corporis optio quae facere eum hic recusandae minima, sit, nisi reiciendis deleniti dolor. Maxime modi corporis laudantium ad fugiat, dolores asperiores voluptatibus architecto nisi, repellat ipsum totam ullam! Harum ullam a, possimus in distinctio quidem nesciunt autem corrupti nulla, vel vero inventore, sequi nobis sint dolorum hic deserunt! Delectus, rem tempore. Illo in magni aliquam nihil itaque labore. Nam quod amet itaque quas doloremque. Ea culpa suscipit rerum nobis, esse, expedita vero eveniet mollitia quidem incidunt eum, veritatis quibusdam deserunt voluptates doloribus tempora recusandae qui dolorum obcaecati illum! Unde, molestiae dolorum placeat veniam, ratione, ex quas qui doloribus eius fugit incidunt recusandae vel? Corrupti, quia tenetur cum dolores doloribus id cupiditate quidem nesciunt expedita. Quo excepturi voluptas amet ipsum sapiente, eos eligendi, autem, commodi cum tempore ut aut? Ipsam illum maxime dolore error aperiam et consequatur sapiente soluta fuga eveniet quas eos, tempora deserunt eaque earum quasi quibusdam perspiciatis illo. Facilis eum totam adipisci modi dolores voluptatibus commodi porro saepe ipsum dicta nostrum, fugiat facere laborum praesentium esse, consequatur iste iure rem. Voluptatem excepturi cupiditate ab quo. Facilis, maxime error iusto ea nemo fugiat! Quasi veritatis, commodi vero obcaecati velit possimus minus aut eveniet, totam esse quae temporibus impedit accusantium maxime doloremque repellat sunt magnam cum dolore officiis! Quam minima dolore cumque blanditiis voluptatem, ipsum nostrum veniam beatae eaque perferendis? Aspernatur excepturi reprehenderit nulla quibusdam, praesentium ex ipsum vero veniam quae animi magnam dolore quasi, hic labore consectetur eos. Repellat fugiat aspernatur libero ut, corporis tenetur ea dignissimos, eaque, excepturi veniam esse minima quaerat repudiandae cumque ipsum at illo nemo atque! Deleniti nobis magnam vero voluptatibus sint totam quos. Officiis eligendi nam qui. Accusantium incidunt autem quaerat doloremque repellat! Tenetur.

      </p>
      <p className="text-dark400_light900">
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quidem, tempora reprehenderit! Fugiat impedit, tempore saepe esse earum velit consectetur perspiciatis corporis optio quae facere eum hic recusandae minima, sit, nisi reiciendis deleniti dolor. Maxime modi corporis laudantium ad fugiat, dolores asperiores voluptatibus architecto nisi, repellat ipsum totam ullam! Harum ullam a, possimus in distinctio quidem nesciunt autem corrupti nulla, vel vero inventore, sequi nobis sint dolorum hic deserunt! Delectus, rem tempore. Illo in magni aliquam nihil itaque labore. Nam quod amet itaque quas doloremque. Ea culpa suscipit rerum nobis, esse, expedita vero eveniet mollitia quidem incidunt eum, veritatis quibusdam deserunt voluptates doloribus tempora recusandae qui dolorum obcaecati illum! Unde, molestiae dolorum placeat veniam, ratione, ex quas qui doloribus eius fugit incidunt recusandae vel? Corrupti, quia tenetur cum dolores doloribus id cupiditate quidem nesciunt expedita. Quo excepturi voluptas amet ipsum sapiente, eos eligendi, autem, commodi cum tempore ut aut? Ipsam illum maxime dolore error aperiam et consequatur sapiente soluta fuga eveniet quas eos, tempora deserunt eaque earum quasi quibusdam perspiciatis illo. Facilis eum totam adipisci modi dolores voluptatibus commodi porro saepe ipsum dicta nostrum, fugiat facere laborum praesentium esse, consequatur iste iure rem. Voluptatem excepturi cupiditate ab quo. Facilis, maxime error iusto ea nemo fugiat! Quasi veritatis, commodi vero obcaecati velit possimus minus aut eveniet, totam esse quae temporibus impedit accusantium maxime doloremque repellat sunt magnam cum dolore officiis! Quam minima dolore cumque blanditiis voluptatem, ipsum nostrum veniam beatae eaque perferendis? Aspernatur excepturi reprehenderit nulla quibusdam, praesentium ex ipsum vero veniam quae animi magnam dolore quasi, hic labore consectetur eos. Repellat fugiat aspernatur libero ut, corporis tenetur ea dignissimos, eaque, excepturi veniam esse minima quaerat repudiandae cumque ipsum at illo nemo atque! Deleniti nobis magnam vero voluptatibus sint totam quos. Officiis eligendi nam qui. Accusantium incidunt autem quaerat doloremque repellat! Tenetur.

      </p>
      <p className="text-dark400_light900">
        Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quidem, tempora reprehenderit! Fugiat impedit, tempore saepe esse earum velit consectetur perspiciatis corporis optio quae facere eum hic recusandae minima, sit, nisi reiciendis deleniti dolor. Maxime modi corporis laudantium ad fugiat, dolores asperiores voluptatibus architecto nisi, repellat ipsum totam ullam! Harum ullam a, possimus in distinctio quidem nesciunt autem corrupti nulla, vel vero inventore, sequi nobis sint dolorum hic deserunt! Delectus, rem tempore. Illo in magni aliquam nihil itaque labore. Nam quod amet itaque quas doloremque. Ea culpa suscipit rerum nobis, esse, expedita vero eveniet mollitia quidem incidunt eum, veritatis quibusdam deserunt voluptates doloribus tempora recusandae qui dolorum obcaecati illum! Unde, molestiae dolorum placeat veniam, ratione, ex quas qui doloribus eius fugit incidunt recusandae vel? Corrupti, quia tenetur cum dolores doloribus id cupiditate quidem nesciunt expedita. Quo excepturi voluptas amet ipsum sapiente, eos eligendi, autem, commodi cum tempore ut aut? Ipsam illum maxime dolore error aperiam et consequatur sapiente soluta fuga eveniet quas eos, tempora deserunt eaque earum quasi quibusdam perspiciatis illo. Facilis eum totam adipisci modi dolores voluptatibus commodi porro saepe ipsum dicta nostrum, fugiat facere laborum praesentium esse, consequatur iste iure rem. Voluptatem excepturi cupiditate ab quo. Facilis, maxime error iusto ea nemo fugiat! Quasi veritatis, commodi vero obcaecati velit possimus minus aut eveniet, totam esse quae temporibus impedit accusantium maxime doloremque repellat sunt magnam cum dolore officiis! Quam minima dolore cumque blanditiis voluptatem, ipsum nostrum veniam beatae eaque perferendis? Aspernatur excepturi reprehenderit nulla quibusdam, praesentium ex ipsum vero veniam quae animi magnam dolore quasi, hic labore consectetur eos. Repellat fugiat aspernatur libero ut, corporis tenetur ea dignissimos, eaque, excepturi veniam esse minima quaerat repudiandae cumque ipsum at illo nemo atque! Deleniti nobis magnam vero voluptatibus sint totam quos. Officiis eligendi nam qui. Accusantium incidunt autem quaerat doloremque repellat! Tenetur.

      </p>
    </div>
  );
}
